import { describe, it, expect } from 'vitest';

/* PDF footer provenance (#411): every page of an exported roadbook says who exported that copy
   and when. The username comes from the signed-in account, so a signed-out export (the public
   /challenge page is open to anyone) must still produce a clean footer, never a dangling label. */

// rb-pdf.js reads RBt at call time; the browser gets it from i18n.js.
globalThis.RBt = (k) => k;
const { provenance } = await import('../public/assets/js/rb-pdf.js');

const WHEN = new Date(2026, 8, 7, 9, 5); // 2026-09-07 09:05 local

describe('provenance', () => {
    it('credits the signed-in user and stamps the local date + time', () => {
        expect(provenance('alvarofranz', WHEN)).toBe('Generated by alvarofranz · 2026-09-07 09:05');
    });

    it('pads a single-digit month, day, hour and minute', () => {
        expect(provenance('', new Date(2026, 0, 2, 3, 4))).toBe('2026-01-02 03:04');
    });

    it('falls back to the timestamp alone when nobody is signed in', () => {
        expect(provenance('', WHEN)).toBe('2026-09-07 09:05');
    });

    it('translates the label through RBt, so the footer follows the UI language', () => {
        globalThis.RBt = (k) => (k === 'Generated by' ? 'Generato da' : k);
        try {
            expect(provenance('maurizio', WHEN)).toBe('Generato da maurizio · 2026-09-07 09:05');
        } finally {
            globalThis.RBt = (k) => k;
        }
    });
});
