import { describe, it, expect } from 'vitest';
import fs from 'fs';

/* The PDF export (#784): its pagination is pure and pinned here; the rest is pinned in the source. */
globalThis.RBt = (k) => k;
const { paginate } = await import('../public/assets/js/rb-pdf.js');
const src = fs.readFileSync('public/assets/js/rb-pdf.js', 'utf8');

describe('paginate', () => {
    it('fills the first page with 4 rows and the next ones with 6', () => {
        expect(paginate(10, false).map((p) => p.to - p.from)).toEqual([4, 6]);
    });
    it('keeps a row free on the last page for the closing QR', () => {
        const pages = paginate(9, true);
        expect(pages.map((p) => p.to - p.from)).toEqual([4, 5]);
        expect(pages[pages.length - 1].closing).toBe(true);
        expect(pages.slice(0, -1).every((p) => !p.closing)).toBe(true);
    });
    it('never leaves the closing block alone on a page: a full last page hands one row over', () => {
        // 4 + 6 fills two pages exactly; with a closing block the second keeps 5 and a third takes 1
        expect(paginate(10, true).map((p) => p.to - p.from)).toEqual([4, 5, 1]);
        expect(paginate(4, true).map((p) => p.to - p.from)).toEqual([3, 1]);
    });
    it('covers every row exactly once, in order', () => {
        for (const n of [1, 3, 4, 5, 9, 10, 11, 16, 23]) for (const closing of [false, true]) {
            const pages = paginate(n, closing);
            expect(pages[0].from).toBe(0);
            pages.forEach((p, i) => { if (i) expect(p.from).toBe(pages[i - 1].to); expect(p.to).toBeGreaterThan(p.from); });
            expect(pages[pages.length - 1].to).toBe(n);
        }
    });
});

describe('what the PDF says (#784)', () => {
    it('has no footer: no "generated by", no file name under the table', () => {
        expect(src).not.toMatch(/Generated by|drawFooter|provenance|\.pdf', PW - RIGHT/);
    });
    it('ends with the digital version and a vector QR, only when there is a link', () => {
        expect(src).toContain("doc.text(RBt('Digital version available online'), LEFT, ty);");
        expect(src).toContain('const qr = RBQr.matrix(link)');
        expect(src).toContain('const pages = paginate(sheet.length, !!link)');
    });
    it('draws the route on the cover unless the roadbook hides its map', () => {
        expect(src).toContain("if (meta.map_access !== false && track.length >= 2) {");
        expect(src).not.toContain('Roadbook produced with RDBK.app');
    });
    it('points the QR at the public page, or at the event it was opened from', () => {
        const ch = fs.readFileSync('public/challenge/challenge.js', 'utf8');
        expect(ch).toContain("const link = j.status === 'public' ? RBPublicLink('/challenge/' + encodeURIComponent(slug)) : (evParam ? RBPublicLink('/event/' + encodeURIComponent(evParam)) : null);");
        const ed = fs.readFileSync('public/editor/editor.js', 'utf8');
        expect(ed).toContain("const link = status === 'public' && publicSlug ? RBPublicLink('/challenge/' + encodeURIComponent(publicSlug)) : null;");
    });
});
