import { describe, it, expect } from 'vitest';
import fs from 'fs';

/* The PDF export (#784 · #810): its pagination is pure and pinned here; the rest is pinned in the source. */
globalThis.RBt = (k) => k;
const { paginate } = await import('../public/assets/js/rb-pdf.js');
const src = fs.readFileSync('public/assets/js/rb-pdf.js', 'utf8');

describe('paginate', () => {
    it('puts 6 rows on every content page, the first one included (#810)', () => {
        expect(paginate(10).map((p) => p.to - p.from)).toEqual([6, 4]);
        expect(paginate(12).map((p) => p.to - p.from)).toEqual([6, 6]);
        expect(paginate(3).map((p) => p.to - p.from)).toEqual([3]);
    });
    it('covers every row exactly once, in order', () => {
        for (const n of [1, 3, 5, 6, 7, 11, 12, 13, 23]) {
            const pages = paginate(n);
            expect(pages[0].from).toBe(0);
            pages.forEach((p, i) => { if (i) expect(p.from).toBe(pages[i - 1].to); expect(p.to).toBeGreaterThan(p.from); });
            expect(pages[pages.length - 1].to).toBe(n);
        }
    });
});

describe('what the PDF says (#784)', () => {
    it('has no footer: no "generated by", no file name under the table', () => {
        expect(src).not.toMatch(/Generated by|drawFooter|provenance|\.pdf', PW - RIGHT/);
    });
    it('one header on every page: the QR top-left when there is a link, no rule under it, nothing after the last note (#810)', () => {
        expect(src).toContain('const qr = link ? RBQr.matrix(link) : null;');
        expect(src).toContain('doc.rect(LEFT + c * cell, qy + r * cell');
        expect(src).not.toMatch(/firstHeader|runHeader|drawClosing|Digital version available online/);
        expect(src).not.toContain('doc.line(LEFT, TOP +');
    });
    it('the cover shows the roadbook image only as the route box backdrop, under a strong veil (#810)', () => {
        expect(src).toContain('drawRoute(doc, track, COVER_MARGIN, boxTop, COVER_W, 118, logo);');
        expect(src).toContain('if (backdrop) drawBackdrop(doc, backdrop, x, y, w, h);');
        expect(src).toContain('doc.setGState(new doc.GState({ opacity: 0.86 }));');
        expect(src).not.toContain('placeLogo');
    });
    it('draws the route on the cover unless the roadbook hides its map', () => {
        expect(src).toContain("if (meta.map_access !== false && track.length >= 2) {");
        expect(src).not.toContain('Roadbook produced with RDBK.app');
    });
    it('points the QR at the public page, or at the event it was opened from', () => {
        const ch = fs.readFileSync('public/challenge/challenge.js', 'utf8');
        expect(ch).toContain("const link = j.status === 'public' ? RBPublicLink('/challenge/' + encodeURIComponent(slug)) : (evParam ? RBPublicLink('/event/' + encodeURIComponent(evParam)) : null);");
        const ed = fs.readFileSync('public/editor/editor.js', 'utf8');
        expect(ed).toContain("const link = status === 'public' && publicSlug ? RBPublicLink('/challenge/' + encodeURIComponent(publicSlug)) : null;");
    });
});
