import { describe, it, expect } from 'vitest';
import fs from 'fs';

/* The PDF export (#784 · #810): its pagination is pure and pinned here; the rest is pinned in the source. */
globalThis.RBt = (k) => k;
const { paginate, geometry } = await import('../public/assets/js/rb-pdf.js');
const src = fs.readFileSync('public/assets/js/rb-pdf.js', 'utf8');

describe('paginate', () => {
    it('puts 6 rows on every content page, the first one included (#810)', () => {
        expect(paginate(10).map((p) => p.to - p.from)).toEqual([6, 4]);
        expect(paginate(12).map((p) => p.to - p.from)).toEqual([6, 6]);
        expect(paginate(3).map((p) => p.to - p.from)).toEqual([3]);
    });
    it('covers every row exactly once, in order', () => {
        for (const n of [1, 3, 5, 6, 7, 11, 12, 13, 23]) {
            const pages = paginate(n);
            expect(pages[0].from).toBe(0);
            pages.forEach((p, i) => { if (i) expect(p.from).toBe(pages[i - 1].to); expect(p.to).toBeGreaterThan(p.from); });
            expect(pages[pages.length - 1].to).toBe(n);
        }
    });
});

describe('what the PDF says (#784)', () => {
    it('has no footer: no "generated by", no file name under the table', () => {
        expect(src).not.toMatch(/Generated by|drawFooter|provenance|\.pdf', PW - RIGHT/);
    });
    it('one header on every page: the QR top-left when there is a link, no rule under it, nothing after the last note (#810)', () => {
        expect(src).toContain('const qr = link ? RBQr.dataURL(link, 256) : null;');
        // one picture, reused on every page — never thousands of squares, which antivirus heuristics read as QR phishing
        expect(src).toContain("doc.addImage(qr, 'PNG', g.left, g.top - 3, QR_SIZE, QR_SIZE, 'rdbk-qr');");
        expect(src).not.toMatch(/firstHeader|runHeader|drawClosing|Digital version available online|qr\.isDark/);
    });
    it('the cover’s backdrop: the image under a strong veil, the map as it is, or nothing (#810 · #973)', () => {
        expect(src).toContain('drawRoute(doc, track, g.left, boxTop, g.width, boxH, backdrop);');
        expect(src).toContain('if (backdrop && backdrop.map && drawImageBox(doc, backdrop.map, x, y, w, h, 0)) return;');
        expect(src).toContain('if (backdrop && backdrop.image) drawImageBox(doc, backdrop.image, x, y, w, h, 0.86);');
        expect(src).toContain("const kind = opts.backdrop || 'image';"); // the image, by default
        expect(src).not.toContain('placeLogo');
    });
    it('says what it is: title, author and creator in its properties', () => {
        expect(src).toContain("creator: 'RDBK.app', keywords: 'roadbook'");
    });
    it('the margins are the reader’s, in cm, the same on the cover and on every page (#973)', () => {
        expect(geometry()).toMatchObject({ top: 15, right: 12, bottom: 12, left: 15, width: 183, bottomY: 285 });
        expect(geometry({ top: 10, right: 10, bottom: 10, left: 10 })).toMatchObject({ width: 190, bottomY: 287 });
        expect(geometry({ left: 1, right: 99 })).toMatchObject({ left: 5, right: 40 }); // kept within 0.5–4 cm
        expect(src).toContain('drawCover(doc, rb, backdrop, when, g);');
        expect(src).toContain("</div>`, 'split');"); // the generator: side by side, the whole screen on a phone
    });
    it('draws the route on the cover unless the roadbook hides its map', () => {
        expect(src).toContain("if (meta.map_access !== false && track.length >= 2) {");
        expect(src).not.toContain('Roadbook produced with RDBK.app');
    });
    it('points the QR at the public page, or at the event it was opened from', () => {
        const ch = fs.readFileSync('public/challenge/challenge.js', 'utf8');
        expect(ch).toContain("const link = j.status === 'public' ? RBPublicLink('/challenge/' + encodeURIComponent(slug)) : (evParam ? RBPublicLink('/event/' + encodeURIComponent(evParam)) : null);");
        expect(ch).toContain("RBPdf.open(rb, { iconBasePath: '/assets/icons/', link });");
        const ed = fs.readFileSync('public/editor/editor.js', 'utf8');
        expect(ed).toContain("const link = status === 'public' && publicSlug ? RBPublicLink('/challenge/' + encodeURIComponent(publicSlug)) : null;");
        expect(ed).toContain('onImage: (image) => { rb.meta.logo = image; setLogoPreview(image); markDirty(); }'); // in the Editor, the roadbook's own image
    });
});

describe('handing the PDF over (#904)', () => {
    it('opens in the system sheet in the app, downloads on the web', () => {
        expect(src).toContain("if (RBIsNativeApp()) await RBShareFile(doc.output('blob'), name, title);");
        expect(src).toContain('else doc.save(name);');
    });
});
